Rename file_handle test suite so it doesn't conflict with a OS type of the same name
```
asio-extensions/test/file_handle.cpp:9:23: error: redefinition of 'file_handle' as different kind of symbol
BOOST_AUTO_TEST_SUITE(file_handle)
                      ^
/usr/include/boost/test/unit_test_suite.hpp:45:11: note: expanded from macro
      'BOOST_AUTO_TEST_SUITE'

namespace suite_name {                                                  \
          ^
/usr/include/x86_64-linux-gnu/bits/fcntl.h:254:8: note: previous definition is here
struct file_handle
       ^
```